import type {Metadata} from "next";
import {NextUIProvider} from "@nextui-org/system";
import "./globals.css";
import Provider from './Provider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <meta charSet="UTF-8"/>
      <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
      <meta httpEquiv="X-UA-Compatible" content="ie=edge"/>
      <title>Document</title>
    </head>
    <body>
    <NextUIProvider>
      <div className="dark text-foreground bg-background">
        <Provider>
          {children}
        </Provider>
      </div>
    </NextUIProvider>
    </body>
    </html>
  );
}
